version: '3'

services:

  nginx:
    container_name: nginx
    image: nginx                     
    build:
      context: .
      dockerfile: ./requirements/nginx/Dockerfile
    ports:
      - "443:443"
    networks:
      - inception
    restart: on-failure
    volumes:
      - volume-wp:/var/www/
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: .
      dockerfile: ./requirements/wordpress/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - inception
    restart: on-failure
    volumes:
      - volume-wp:/var/www/
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: .
      dockerfile: ./requirements/mariadb/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_ROOT: ${DB_ROOT}
    networks:
      - inception
    restart: on-failure
    volumes:
      - volume-db:/var/lib/mysql

volumes:
  volume-wp:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress

  volume-db:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb

networks:
    inception:
        driver: bridge
