version: '3'

services:

  nginx:
    container_name: nginx
    image: nginx                     
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    ports:
      - "443:443"
    networks:
      - inception
    restart: on-failure
    volumes:
      - ./requirements/nginx/tools/cert:/etc/nginx/ssl
      - volume-wp:/var/www/
    depends_on:
      - wordpress

  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
    ports:
      - "9000:9000"
    networks:
      - inception
    restart: on-failure
    volumes:
      - volume-wp:/var/www/
    depends_on:
      - mariadb

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
        DB_ROOT: ${DB_ROOT}
    ports:
      - "3306:3306"
    networks:
      - inception
    restart: on-failure
    volumes:
      - volume-db:/var/lib/mysql

volumes:
  volume-wp:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress

  volume-db:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb

networks:
    inception:
        driver: bridge
