version: "3"

services:
  nginx:
    restart: always
    depends_on:
      - wordpress
      - adminer
      - badge42
      - simple-portfolio
    build:
      context: requirements/nginx
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - intra
    ports:
      - "443:443"
    env_file:
      - .env
  wordpress:
    restart: always
    depends_on:
      - mariadb
      - redis
    build:
      context: requirements/wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - intra
    expose:
      - "9000"
    env_file:
      - .env
  mariadb:
    restart: always
    build:
      context: requirements/mariadb
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - intra
    expose:
      - "3306"
    env_file:
      - .env
  

networks:
  intra:
    driver: bridge

volumes:
  db_data:
    driver_opts:
      type: "none"
      o: "bind"
      device: "~/data/db_data"
  wordpress_data:
    driver_opts:
      type: "none"
      o: "bind"
      device: "~/data/wordpress_data"
